<?php

namespace App\Services;

/**
 * ReportRenderer — the pure JSON/Markdown/HTML rendering/templating logic
 * for ReportExportService, extracted (CODE-STRUCT-DECOMPOSE) so rendering
 * is decoupled from the Eloquent-querying build*Report() methods that
 * assemble the data it renders. Zero DB/Eloquent dependency — takes an
 * already-assembled, already-redacted data array and a format string, and
 * returns the rendered content string.
 *
 * All methods are static: nothing here holds instance state, matching the
 * pure-logic seam pattern already used for internal/cef, alert_identity.py,
 * incident_aggregation.py, and ThreatHuntQueryAllowlist elsewhere in this
 * codebase.
 */
class ReportRenderer
{
    private static function renderJson(array $data): string
    {
        return json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    }

    private static function renderMarkdown(array $data): string
    {
        $meta  = $data['export_meta'];
        $lines = [];

        $lines[] = "# {$meta['report_type_label']}";
        $lines[] = '';
        $lines[] = '> ⚠️ **Advisory Notice:** ' . ReportExportService::DISCLAIMER;
        $lines[] = '';
        $lines[] = '## Export Metadata';
        $lines[] = '';
        $lines[] = '| Field | Value |';
        $lines[] = '|-------|-------|';
        $lines[] = '| Report Type | ' . $meta['report_type_label'] . ' |';
        $lines[] = '| Generated At | ' . $meta['generated_at'] . ' |';
        $lines[] = '| Generated By | ' . $meta['generated_by'] . ' |';

        if (!empty($meta['export_reason'])) {
            $lines[] = '| Export Reason | ' . $meta['export_reason'] . ' |';
        }

        $lines[] = '| Source ID | ' . $meta['source_id'] . ' |';
        $lines[] = '';

        switch ($meta['report_type']) {
            case 'investigation':
                $lines = array_merge($lines, self::mdInvestigation($data));
                break;
            case 'response_plan':
                $lines = array_merge($lines, self::mdResponsePlan($data));
                break;
            case 'entity_risk':
                $lines = array_merge($lines, self::mdEntityRisk($data));
                break;
            case 'trace':
                $lines = array_merge($lines, self::mdTrace($data));
                break;
        }

        $lines[] = '';
        $lines[] = '---';
        $lines[] = '_Generated by XDR Platform | ' . $meta['generated_at'] . '_';

        return implode("\n", $lines);
    }

    private static function renderHtml(array $data): string
    {
        $meta  = $data['export_meta'];
        $style = self::htmlStyles();
        $title = htmlspecialchars($meta['report_type_label']);
        $by    = htmlspecialchars($meta['generated_by']);
        $at    = htmlspecialchars($meta['generated_at']);
        $disc  = htmlspecialchars(ReportExportService::DISCLAIMER);
        $srcId = htmlspecialchars($meta['source_id']);
        $reason = !empty($meta['export_reason']) ? htmlspecialchars($meta['export_reason']) : '—';

        $body = self::htmlBody($data);

        return <<<HTML
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{$title}</title>
<style>{$style}</style>
</head>
<body>
<div class="report-header">
  <h1>{$title}</h1>
  <div class="meta-grid">
    <div><span class="meta-label">Generated</span>{$at}</div>
    <div><span class="meta-label">By</span>{$by}</div>
    <div><span class="meta-label">Source ID</span><code>{$srcId}</code></div>
    <div><span class="meta-label">Reason</span>{$reason}</div>
  </div>
</div>

<div class="disclaimer-box">
  <strong>⚠️ Advisory Notice:</strong> {$disc}
</div>

{$body}

<div class="report-footer">
  <p>XDR Platform | {$title} | Generated {$at} | Source: {$srcId}</p>
</div>
</body>
</html>
HTML;
    }

    // -------------------------------------------------------------------------
    // Markdown section builders
    // -------------------------------------------------------------------------

    private static function mdInvestigation(array $data): array
    {
        $inv   = $data['investigation'] ?? [];
        $lines = [];

        $lines[] = '## Investigation Details';
        $lines[] = '';
        $lines[] = '| Field | Value |';
        $lines[] = '|-------|-------|';

        foreach (['investigation_id', 'title', 'state', 'severity', 'priority', 'creator_name', 'assignee_name'] as $f) {
            if (isset($inv[$f])) {
                $lines[] = '| ' . ucwords(str_replace('_', ' ', $f)) . ' | ' . $inv[$f] . ' |';
            }
        }

        $lines[] = '';
        $lines[] = '## State History';
        $lines[] = '';

        foreach ($data['state_history'] ?? [] as $evt) {
            $evt = (array) $evt;
            $lines[] = '- `' . ($evt['occurred_at'] ?? '') . '` **' . ($evt['from_state'] ?? '?') . '** → **' . ($evt['to_state'] ?? '?') . '** by ' . ($evt['actor_name'] ?? 'system');
        }

        $lines[] = '';
        $lines[] = '## Assignment History';
        $lines[] = '';

        foreach ($data['assignment_history'] ?? [] as $a) {
            $a = (array) $a;
            $lines[] = '- `' . ($a['assigned_at'] ?? '') . '` → **' . ($a['assignee_name'] ?? 'unknown') . '** (' . ($a['is_active'] ? 'active' : 'past') . ')';
        }

        $lines[] = '';
        $lines[] = '## Analyst Notes';
        $lines[] = '';

        foreach ($data['analyst_notes'] ?? [] as $note) {
            $note = (array) $note;
            $lines[] = '### ' . ($note['note_type'] ?? 'note') . ' — `' . ($note['created_at'] ?? '') . '`';
            $lines[] = '';
            $lines[] = ($note['body'] ?? '');
            $lines[] = '';
        }

        $lines[] = '## Linked Alerts';
        $lines[] = '';
        $lines[] = '| Alert ID | Type | Severity | Detected At |';
        $lines[] = '|---------|------|----------|-------------|';

        foreach ($data['linked_alerts'] ?? [] as $al) {
            $al = (array) $al;
            $lines[] = '| ' . ($al['alert_id'] ?? '') . ' | ' . ($al['alert_type'] ?? '') . ' | ' . ($al['severity'] ?? '') . ' | ' . ($al['detected_at'] ?? '') . ' |';
        }

        $lines[] = '';

        return $lines;
    }

    private static function mdResponsePlan(array $data): array
    {
        $plan  = $data['response_plan'] ?? [];
        $lines = [];

        $lines[] = '## Response Plan Details';
        $lines[] = '';
        $lines[] = '| Field | Value |';
        $lines[] = '|-------|-------|';

        foreach (['plan_id', 'title', 'state', 'risk_level', 'creator_name'] as $f) {
            if (isset($plan[$f])) {
                $lines[] = '| ' . ucwords(str_replace('_', ' ', $f)) . ' | ' . $plan[$f] . ' |';
            }
        }

        $lines[] = '';
        $lines[] = '## Recommended Actions';
        $lines[] = '';
        $lines[] = '| Action | Target | Status | Advisory Only | Reasoning |';
        $lines[] = '|--------|--------|--------|---------------|-----------|';

        foreach ($data['actions'] ?? [] as $act) {
            $act = (array) $act;
            $advisory = $act['advisory_only'] ? '✓ yes' : 'no';
            $lines[] = '| `' . ($act['action_type'] ?? '') . '` | ' . ($act['target_entity_key'] ?? '') . ' | ' . ($act['status'] ?? '') . ' | ' . $advisory . ' | ' . Str_limit($act['reasoning'] ?? '', 60) . ' |';
        }

        $lines[] = '';
        $lines[] = '## Approval Chain';
        $lines[] = '';

        foreach ($data['full_approval_history'] ?? [] as $appr) {
            $appr = (array) $appr;
            $lines[] = '- `' . ($appr['decision_at'] ?? '') . '` **' . ($appr['decision'] ?? '') . '** by ' . ($appr['approver_name'] ?? 'unknown');
            if (!empty($appr['notes'])) {
                $lines[] = '  - Note: ' . $appr['notes'];
            }
        }

        $lines[] = '';

        return $lines;
    }

    private static function mdEntityRisk(array $data): array
    {
        $entity = $data['entity'] ?? [];
        $risk   = $data['current_risk'] ?? [];
        $lines  = [];

        $lines[] = '## Entity';
        $lines[] = '';
        $lines[] = '| Field | Value |';
        $lines[] = '|-------|-------|';
        $lines[] = '| Type | ' . ($entity['entity_type'] ?? '') . ' |';
        $lines[] = '| Key | `' . ($entity['entity_key'] ?? '') . '` |';
        $lines[] = '| Risk Score | **' . number_format((float) ($risk['risk_score'] ?? 0), 1) . ' / 10** |';
        $lines[] = '| Risk Level | **' . strtoupper($risk['risk_level'] ?? 'unknown') . '** |';
        $lines[] = '| Calculated At | ' . ($risk['calculated_at'] ?? '—') . ' |';
        $lines[] = '';
        $lines[] = '## Contributing Risk Factors';
        $lines[] = '';
        $lines[] = '| Factor | Value | Weight | Contribution | Advisory Only |';
        $lines[] = '|--------|-------|--------|--------------|---------------|';

        foreach ($risk['risk_factors'] ?? [] as $f) {
            $f = (array) $f;
            $adv = empty($f['advisory_only']) ? 'no' : '✓ yes (shadow domain)';
            $lines[] = '| `' . ($f['factor'] ?? '') . '` | ' . ($f['value'] ?? 0) . ' | ' . number_format((float) ($f['weight'] ?? 0), 1) . ' | ' . number_format((float) ($f['contribution'] ?? 0), 2) . ' | ' . $adv . ' |';
        }

        $lines[] = '';
        $lines[] = '## Historical Snapshots';
        $lines[] = '';
        $lines[] = '| Calculated At | Score | Level |';
        $lines[] = '|---------------|-------|-------|';

        foreach ($data['historical_snapshots'] ?? [] as $snap) {
            $snap = (array) $snap;
            $lines[] = '| ' . ($snap['calculated_at'] ?? '') . ' | ' . number_format((float) ($snap['risk_score'] ?? 0), 1) . ' | ' . ($snap['risk_level'] ?? '') . ' |';
        }

        $lines[] = '';

        return $lines;
    }

    private static function mdTrace(array $data): array
    {
        $trace = $data['trace'] ?? [];
        $lines = [];

        $lines[] = '## Trace';
        $lines[] = '';
        $lines[] = '| Field | Value |';
        $lines[] = '|-------|-------|';
        $lines[] = '| Trace ID | `' . ($trace['trace_id'] ?? '') . '` |';
        $lines[] = '| First Seen | ' . ($trace['first_seen'] ?? '—') . ' |';
        $lines[] = '| Last Seen | ' . ($trace['last_seen'] ?? '—') . ' |';
        $lines[] = '| Alerts | ' . ($trace['alert_count'] ?? 0) . ' |';
        $lines[] = '| Incidents | ' . ($trace['incident_count'] ?? 0) . ' |';
        $lines[] = '| Pipeline Events | ' . ($trace['op_event_count'] ?? 0) . ' |';
        $lines[] = '';
        $lines[] = '## Alerts Generated';
        $lines[] = '';
        $lines[] = '| Alert Type | Severity | Detected At |';
        $lines[] = '|------------|----------|-------------|';

        foreach ($data['alerts_generated'] ?? [] as $al) {
            $al = (array) $al;
            $lines[] = '| ' . ($al['alert_type'] ?? '') . ' | ' . ($al['severity'] ?? '') . ' | ' . ($al['detected_at'] ?? '') . ' |';
        }

        $lines[] = '';
        $lines[] = '## Pipeline Event Chain';
        $lines[] = '';

        foreach ($data['pipeline_stages'] ?? [] as $evt) {
            $evt = (array) $evt;
            $lines[] = '- `' . ($evt['occurred_at'] ?? '') . '` [' . ($evt['source_service'] ?? '') . '] ' . ($evt['event_type'] ?? '');
        }

        $lines[] = '';

        return $lines;
    }

    // -------------------------------------------------------------------------
    // HTML body builder
    // -------------------------------------------------------------------------

    private static function htmlBody(array $data): string
    {
        $type = $data['export_meta']['report_type'];
        $h = '';

        switch ($type) {
            case 'investigation':
                $h .= self::htmlInvestigation($data);
                break;
            case 'response_plan':
                $h .= self::htmlResponsePlan($data);
                break;
            case 'entity_risk':
                $h .= self::htmlEntityRisk($data);
                break;
            case 'trace':
                $h .= self::htmlTrace($data);
                break;
        }

        return $h;
    }

    private static function htmlInvestigation(array $data): string
    {
        $inv = $data['investigation'] ?? [];
        $h   = self::htmlSection('Investigation Details', self::htmlKvTable([
            'ID'         => $inv['investigation_id'] ?? '—',
            'Title'      => $inv['title'] ?? '—',
            'State'      => '<code>' . ($inv['state'] ?? '—') . '</code>',
            'Severity'   => strtoupper($inv['severity'] ?? '—'),
            'Priority'   => 'P' . ($inv['priority'] ?? '—'),
            'Created By' => $inv['creator_name'] ?? '—',
            'Assigned To'=> $inv['assignee_name'] ?? 'Unassigned',
        ]));

        if (!empty($inv['description'])) {
            $h .= self::htmlSection('Description', '<p>' . htmlspecialchars($inv['description']) . '</p>');
        }

        if (!empty($data['state_history'])) {
            $rows = array_map(fn($e) => [
                'Timestamp' => ((array)$e)['occurred_at'] ?? '',
                'From' => ((array)$e)['from_state'] ?? '',
                'To'   => ((array)$e)['to_state'] ?? '',
                'By'   => ((array)$e)['actor_name'] ?? 'system',
            ], $data['state_history']);
            $h .= self::htmlSection('State History', self::htmlTable(['Timestamp','From','To','By'], $rows));
        }

        if (!empty($data['assignment_history'])) {
            $rows = array_map(fn($a) => [
                'Assigned At' => ((array)$a)['assigned_at'] ?? '',
                'Assignee'    => ((array)$a)['assignee_name'] ?? '',
                'Status'      => ((array)$a)['is_active'] ? 'active' : 'past',
            ], $data['assignment_history']);
            $h .= self::htmlSection('Assignment History', self::htmlTable(['Assigned At','Assignee','Status'], $rows));
        }

        if (!empty($data['analyst_notes'])) {
            $noteHtml = '';
            foreach ($data['analyst_notes'] as $note) {
                $note = (array) $note;
                $noteHtml .= '<div class="note-card"><div class="note-meta"><span class="badge">' . htmlspecialchars($note['note_type'] ?? 'note') . '</span> ' . htmlspecialchars($note['created_at'] ?? '') . '</div><p>' . htmlspecialchars($note['body'] ?? '') . '</p></div>';
            }
            $h .= self::htmlSection('Analyst Notes', $noteHtml);
        }

        if (!empty($data['linked_alerts'])) {
            $rows = array_map(fn($a) => [
                'Alert Type' => ((array)$a)['alert_type'] ?? '',
                'Severity'   => ((array)$a)['severity'] ?? '',
                'Actor'      => ((array)$a)['actor_key'] ?? '—',
                'Detected At'=> ((array)$a)['detected_at'] ?? '',
            ], $data['linked_alerts']);
            $h .= self::htmlSection('Linked Alerts', self::htmlTable(['Alert Type','Severity','Actor','Detected At'], $rows));
        }

        return $h;
    }

    private static function htmlResponsePlan(array $data): string
    {
        $plan = $data['response_plan'] ?? [];
        $h    = self::htmlSection('Response Plan Details', self::htmlKvTable([
            'Plan ID'   => $plan['plan_id'] ?? '—',
            'Title'     => $plan['title'] ?? '—',
            'State'     => '<code>' . ($plan['state'] ?? '—') . '</code>',
            'Risk Level'=> strtoupper($plan['risk_level'] ?? '—'),
            'Created By'=> $plan['creator_name'] ?? '—',
        ]));

        if (!empty($data['actions'])) {
            $rows = array_map(function ($a) {
                $a = (array) $a;
                return [
                    'Action'        => '<code>' . ($a['action_type'] ?? '') . '</code>',
                    'Target'        => htmlspecialchars($a['target_entity_key'] ?? ''),
                    'Status'        => $a['status'] ?? '',
                    'Advisory Only' => !empty($a['advisory_only']) ? '<span class="advisory-badge">advisory_only</span>' : 'standard',
                    'Reasoning'     => htmlspecialchars(substr($a['reasoning'] ?? '', 0, 80)),
                ];
            }, $data['actions']);
            $h .= self::htmlSection('Recommended Actions (Planning Only)', self::htmlTable(['Action','Target','Status','Advisory Only','Reasoning'], $rows));
        }

        if (!empty($data['full_approval_history'])) {
            $rows = array_map(fn($a) => [
                'Decision'    => ((array)$a)['decision'] ?? '',
                'Approver'    => ((array)$a)['approver_name'] ?? '',
                'Decision At' => ((array)$a)['decision_at'] ?? '',
                'Notes'       => htmlspecialchars(substr(((array)$a)['notes'] ?? '', 0, 80)),
            ], $data['full_approval_history']);
            $h .= self::htmlSection('Approval Chain', self::htmlTable(['Decision','Approver','Decision At','Notes'], $rows));
        }

        return $h;
    }

    private static function htmlEntityRisk(array $data): string
    {
        $entity = $data['entity'] ?? [];
        $risk   = $data['current_risk'] ?? [];

        $h = self::htmlSection('Entity', self::htmlKvTable([
            'Type'          => $entity['entity_type'] ?? '—',
            'Key'           => '<code>' . htmlspecialchars($entity['entity_key'] ?? '') . '</code>',
            'Risk Score'    => '<strong>' . number_format((float)($risk['risk_score'] ?? 0), 1) . ' / 10</strong>',
            'Risk Level'    => '<strong>' . strtoupper($risk['risk_level'] ?? '—') . '</strong>',
            'Calculated At' => $risk['calculated_at'] ?? '—',
        ]));

        if (!empty($risk['risk_factors'])) {
            $rows = array_map(function ($f) {
                $f = (array) $f;
                return [
                    'Factor'       => '<code>' . ($f['factor'] ?? '') . '</code>',
                    'Value'        => $f['value'] ?? 0,
                    'Weight'       => number_format((float)($f['weight'] ?? 0), 1),
                    'Contribution' => number_format((float)($f['contribution'] ?? 0), 2),
                    'Advisory'     => !empty($f['advisory_only']) ? '<span class="advisory-badge">shadow domain</span>' : '—',
                ];
            }, $risk['risk_factors']);
            $h .= self::htmlSection('Contributing Risk Factors', self::htmlTable(['Factor','Value','Weight','Contribution','Advisory'], $rows));
        }

        if (!empty($data['historical_snapshots'])) {
            $rows = array_map(fn($s) => [
                'Calculated At' => ((array)$s)['calculated_at'] ?? '',
                'Score'         => number_format((float)((array)$s)['risk_score'] ?? 0, 1),
                'Level'         => strtoupper(((array)$s)['risk_level'] ?? ''),
            ], $data['historical_snapshots']);
            $h .= self::htmlSection('Risk History', self::htmlTable(['Calculated At','Score','Level'], $rows));
        }

        return $h;
    }

    private static function htmlTrace(array $data): string
    {
        $trace = $data['trace'] ?? [];
        $h     = self::htmlSection('Trace Summary', self::htmlKvTable([
            'Trace ID'       => '<code>' . htmlspecialchars($trace['trace_id'] ?? '') . '</code>',
            'First Seen'     => $trace['first_seen'] ?? '—',
            'Last Seen'      => $trace['last_seen'] ?? '—',
            'Alerts'         => $trace['alert_count'] ?? 0,
            'Incidents'      => $trace['incident_count'] ?? 0,
            'Pipeline Events'=> $trace['op_event_count'] ?? 0,
        ]));

        if (!empty($data['alerts_generated'])) {
            $rows = array_map(fn($a) => [
                'Alert Type'  => ((array)$a)['alert_type'] ?? '',
                'Severity'    => ((array)$a)['severity'] ?? '',
                'Detected At' => ((array)$a)['detected_at'] ?? '',
            ], $data['alerts_generated']);
            $h .= self::htmlSection('Alerts Generated', self::htmlTable(['Alert Type','Severity','Detected At'], $rows));
        }

        if (!empty($data['pipeline_stages'])) {
            $rows = array_map(fn($e) => [
                'Occurred At'   => ((array)$e)['occurred_at'] ?? '',
                'Service'       => ((array)$e)['source_service'] ?? '',
                'Event Type'    => ((array)$e)['event_type'] ?? '',
            ], $data['pipeline_stages']);
            $h .= self::htmlSection('Pipeline Event Chain', self::htmlTable(['Occurred At','Service','Event Type'], $rows));
        }

        return $h;
    }

    // -------------------------------------------------------------------------
    // HTML primitives
    // -------------------------------------------------------------------------

    private static function htmlSection(string $title, string $content): string
    {
        return '<section><h2>' . htmlspecialchars($title) . '</h2>' . $content . '</section>';
    }

    private static function htmlKvTable(array $pairs): string
    {
        $rows = '';
        foreach ($pairs as $k => $v) {
            $rows .= '<tr><th>' . htmlspecialchars($k) . '</th><td>' . $v . '</td></tr>';
        }
        return '<table>' . $rows . '</table>';
    }

    private static function htmlTable(array $headers, array $rows): string
    {
        if (empty($rows)) {
            return '<p class="empty">No records.</p>';
        }
        $ths = implode('', array_map(fn($h) => '<th>' . htmlspecialchars($h) . '</th>', $headers));
        $trs = '';
        foreach ($rows as $row) {
            $tds = implode('', array_map(fn($v) => '<td>' . $v . '</td>', array_values($row)));
            $trs .= '<tr>' . $tds . '</tr>';
        }
        return '<table><thead><tr>' . $ths . '</tr></thead><tbody>' . $trs . '</tbody></table>';
    }

    private static function htmlStyles(): string
    {
        return '
*{box-sizing:border-box;margin:0;padding:0}
body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;font-size:13px;line-height:1.5;color:#1a1a2e;max-width:1000px;margin:0 auto;padding:24px;background:#fff}
h1{font-size:22px;color:#0f3460;margin-bottom:12px;border-bottom:3px solid #0f3460;padding-bottom:8px}
h2{font-size:15px;color:#16213e;margin:24px 0 10px;border-bottom:1px solid #dee2e6;padding-bottom:4px}
.report-header{margin-bottom:20px}
.meta-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:8px;background:#f8f9fa;padding:12px;border-radius:4px;margin-top:12px}
.meta-label{display:block;font-size:11px;color:#6c757d;text-transform:uppercase;letter-spacing:.05em}
code{font-family:monospace;background:#e9ecef;padding:1px 4px;border-radius:3px;font-size:12px}
.disclaimer-box{background:#fff3cd;border:1px solid #ffc107;padding:12px 16px;border-radius:4px;margin:16px 0;font-size:13px}
section{margin-bottom:24px}
table{width:100%;border-collapse:collapse;margin:8px 0;font-size:12px}
th,td{border:1px solid #dee2e6;padding:6px 10px;text-align:left}
th{background:#f8f9fa;font-weight:600;white-space:nowrap}
tr:nth-child(even){background:#f8f9fa}
.advisory-badge{background:#fff3cd;border:1px solid #ffc107;padding:1px 6px;border-radius:3px;font-size:11px;white-space:nowrap}
.note-card{border:1px solid #dee2e6;border-radius:4px;padding:12px;margin-bottom:8px}
.note-meta{font-size:11px;color:#6c757d;margin-bottom:6px}
.badge{background:#e9ecef;padding:1px 6px;border-radius:10px;font-size:11px}
.empty{color:#6c757d;font-style:italic;padding:8px 0}
.report-footer{margin-top:32px;padding-top:12px;border-top:1px solid #dee2e6;font-size:11px;color:#6c757d;text-align:center}
@media print{.no-print{display:none}body{max-width:none;padding:10px}h1{font-size:18px}h2{font-size:13px}}
';
    }

    public static function render(array $data, string $format): string
    {
        return match ($format) {
            'json'     => self::renderJson($data),
            'markdown' => self::renderMarkdown($data),
            'html'     => self::renderHtml($data),
            default    => throw new \InvalidArgumentException("Unsupported format: {$format}"),
        };
    }
}
