<?php

return [
    'api_rate_limit_per_minute' => env('SOC_API_RATE_LIMIT_PER_MINUTE', 120),
    'export_max_rows' => env('SOC_EXPORT_MAX_ROWS', 500),
    'webhook_secret' => env('SOC_WEBHOOK_SECRET'),
    'agent_enrollment_token' => env('SOC_AGENT_ENROLLMENT_TOKEN'),
    'agent_heartbeat_interval_seconds' => env('SOC_AGENT_HEARTBEAT_INTERVAL_SECONDS', 60),
    'agent_offline_after_seconds' => env('SOC_AGENT_OFFLINE_AFTER_SECONDS', 180),
    'agent_latest_version' => env('SOC_AGENT_LATEST_VERSION', '0.2.0'),
    'agent_retry_queue_alert_threshold' => env('SOC_AGENT_RETRY_QUEUE_ALERT_THRESHOLD', 1000),
    'agent_delivery_failure_alert_threshold' => env('SOC_AGENT_DELIVERY_FAILURE_ALERT_THRESHOLD', 5),
    'ai_provider' => env('SOC_AI_PROVIDER', 'local'),
    'ai_service_enabled' => env('SOC_AI_SERVICE_ENABLED', false),
    'ai_service_url' => env('XDR_AI_RAG_SERVICE_URL', 'http://127.0.0.1:8094'),
    'ai_enabled' => env('SOC_AI_ENABLED', true),
    'ai_model' => env('SOC_AI_MODEL', 'local-heuristic'),
    'ai_timeout_seconds' => env('SOC_AI_TIMEOUT_SECONDS', 20),
    'ai_retry_attempts' => env('SOC_AI_RETRY_ATTEMPTS', 1),
    'openai_compatible_base_url' => env('SOC_OPENAI_COMPATIBLE_BASE_URL', ''),
    'openai_compatible_api_key' => env('SOC_OPENAI_COMPATIBLE_API_KEY', ''),
    'ollama_base_url' => env('SOC_OLLAMA_BASE_URL', 'http://127.0.0.1:11434'),
    'ollama_model' => env('SOC_OLLAMA_MODEL', 'llama3.1'),
    'ti_virustotal_api_key' => env('SOC_TI_VIRUSTOTAL_API_KEY', ''),
    'ti_abuseipdb_api_key' => env('SOC_TI_ABUSEIPDB_API_KEY', ''),
    'ti_misp_base_url' => env('SOC_TI_MISP_BASE_URL', ''),
    'ti_misp_api_key' => env('SOC_TI_MISP_API_KEY', ''),
    'ti_opencti_base_url' => env('SOC_TI_OPENCTI_BASE_URL', ''),
    'ti_opencti_api_key' => env('SOC_TI_OPENCTI_API_KEY', ''),
    'ti_webhook_url' => env('SOC_TI_WEBHOOK_URL', ''),
    'rag_vector_store' => env('SOC_RAG_VECTOR_STORE', 'local-keyword'),
    'rag_embedding_provider' => env('SOC_RAG_EMBEDDING_PROVIDER', 'local-keyword'),
    'qdrant_base_url' => env('SOC_QDRANT_BASE_URL', 'http://127.0.0.1:6333'),
    'qdrant_collection' => env('SOC_QDRANT_COLLECTION', 'soc_knowledge'),
    'quality_alert_volume_spike_ratio' => env('SOC_QUALITY_ALERT_VOLUME_SPIKE_RATIO', 2.0),
    'quality_fp_spike_ratio' => env('SOC_QUALITY_FP_SPIKE_RATIO', 1.5),
    'permissions' => [
        'admin' => [
            'dashboard.view',
            'exports.view',
            'incidents.view',
            'incidents.update',
            'workflow.execute',
            'rules.manage',
            'agents.manage',
            'exports.run',
            'audit.view',
        ],
        'analyst' => [
            'dashboard.view',
            'exports.view',
            'incidents.view',
            'incidents.update',
            'workflow.execute',
            'agents.manage',
            'exports.run',
            'audit.view',
        ],
        'viewer' => [
            'dashboard.view',
            'incidents.view',
            'audit.view',
            'exports.view',
        ],
    ],
];
