"""
Adds 40 new shadow detection rules to the registry for Detection Depth Phase 2.
Categories:
  - Credential Abuse (7)
  - Persistence Chains (7)
  - Defense Evasion (6)
  - Lateral Movement (7)
  - Cloud / SaaS (7)
  - Container / Runtime (6)
Total: 40 new rules -> 133 total
"""
import json
import sys

NEW_RULES = [
    # ── Credential Abuse (7) ──────────────────────────────────────────────────
    {
        "rule_id": "CRED_KERBEROS_ANOMALOUS_TGT_REQUEST",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Anomalous Kerberos TGT Request",
        "description": "Detects unusual Kerberos TGT requests from non-standard processes or at atypical hours. Indicator of pass-the-ticket or AS-REP roasting activity.",
        "severity": "high",
        "confidence": 0.72,
        "mitre_attack": ["T1558", "T1558.003"],
        "event_types": ["security_event"],
        "required_fields": ["event_id", "process_name", "user", "timestamp"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|user",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Scheduled tasks and service accounts may generate TGTs at non-standard hours.",
        "suppression_guidance": "Suppress by known service account patterns with documented schedules.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CRED_PASS_THE_HASH_INDICATOR",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Pass-the-Hash Indicator",
        "description": "Detects NTLM authentication attempts where the source process lacks a corresponding interactive logon. Indicates lateral movement via stolen NTLM hashes.",
        "severity": "critical",
        "confidence": 0.78,
        "mitre_attack": ["T1550.002"],
        "event_types": ["security_event", "process_event"],
        "required_fields": ["event_id", "process_name", "user", "auth_package"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|user|host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Certain Windows services use NTLM without interactive logon by design.",
        "suppression_guidance": "Allowlist specific service accounts with documented NTLM usage patterns.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CRED_TOKEN_REPLAY_INDICATOR",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Token Replay Indicator",
        "description": "Detects reuse of authentication tokens across geographically distant sources within a short window. Indicates stolen token replay attacks.",
        "severity": "high",
        "confidence": 0.81,
        "mitre_attack": ["T1528", "T1550"],
        "event_types": ["login_success", "saas_event"],
        "required_fields": ["user", "source_ip", "timestamp", "token_id"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|user",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "VPN users may appear geographically distant from their physical location.",
        "suppression_guidance": "Suppress known VPN exit nodes with allowlisted IP ranges.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CRED_MFA_FATIGUE_PATTERN",
        "domain": "identity",
        "status": "shadow",
        "version": "v1",
        "title": "MFA Fatigue / Push Spam Pattern",
        "description": "Detects rapid successive MFA push notifications to the same user indicating MFA fatigue (push spam) attacks. Threshold: 5+ pushes within 5 minutes.",
        "severity": "high",
        "confidence": 0.85,
        "mitre_attack": ["T1621"],
        "event_types": ["mfa_pushed", "mfa_failed"],
        "required_fields": ["user", "mfa_method", "timestamp"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|user",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Users with unreliable network may retry MFA pushes legitimately.",
        "suppression_guidance": "Suppress for users with documented MFA reliability issues.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CRED_IMPOSSIBLE_PRIVILEGE_ESCALATION_CHAIN",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Impossible Privilege Escalation Chain",
        "description": "Detects privilege escalation sequence where a standard user process acquires SYSTEM-level privileges through an atypical parent-child chain without a known elevation prompt.",
        "severity": "critical",
        "confidence": 0.80,
        "mitre_attack": ["T1068", "T1134"],
        "event_types": ["process_event", "security_event"],
        "required_fields": ["process_name", "parent_process_name", "integrity_level", "user"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|host|user",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Legitimate software installers may trigger UAC elevation with unusual parent chains.",
        "suppression_guidance": "Baseline known installer processes and suppress by signed binary + publisher.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CRED_ABNORMAL_LSASS_MEMORY_ACCESS",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Abnormal LSASS Memory Access",
        "description": "Detects non-system processes opening LSASS with memory read permissions. Indicator of credential dumping via process injection or direct API calls.",
        "severity": "critical",
        "confidence": 0.88,
        "mitre_attack": ["T1003.001"],
        "event_types": ["sysmon_event"],
        "required_fields": ["source_process", "target_process", "access_mask"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "AV/EDR products legitimately read LSASS for scanning.",
        "suppression_guidance": "Allowlist signed security product processes by certificate.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CRED_DCSync_REPLICATION_REQUEST",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "DCSync Replication Request from Non-DC",
        "description": "Detects Active Directory replication API calls (DrsGetNCChanges) originating from non-domain-controller machines. Indicates DCSync credential theft.",
        "severity": "critical",
        "confidence": 0.92,
        "mitre_attack": ["T1003.006"],
        "event_types": ["security_event"],
        "required_fields": ["event_id", "source_host", "target", "flags"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|source_host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Legitimate AD sync tools and Azure AD Connect may trigger replication.",
        "suppression_guidance": "Suppress for known sync server IP ranges with documented AD Connect configuration.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    # ── Persistence Chains (7) ────────────────────────────────────────────────
    {
        "rule_id": "PERSIST_BROWSER_EXTENSION_INSTALL",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Suspicious Browser Extension Installation",
        "description": "Detects silent browser extension installation via command line or registry without user interaction. Indicates persistence via browser hijacking.",
        "severity": "medium",
        "confidence": 0.65,
        "mitre_attack": ["T1176"],
        "event_types": ["registry_event", "process_event"],
        "required_fields": ["process_name", "registry_key", "user"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|extension_id",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Enterprise browser management tools install extensions silently by policy.",
        "suppression_guidance": "Suppress known enterprise extension IDs from GPO baseline.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "PERSIST_WMI_EVENT_SUBSCRIPTION",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "WMI Event Subscription Persistence",
        "description": "Detects creation of WMI event consumer and filter subscriptions that execute commands on system events. Indicates fileless persistence via WMI.",
        "severity": "high",
        "confidence": 0.83,
        "mitre_attack": ["T1546.003"],
        "event_types": ["wmi_event"],
        "required_fields": ["consumer_name", "filter_name", "command_line"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|consumer_name",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Enterprise monitoring tools (SCCM, monitoring agents) use WMI subscriptions.",
        "suppression_guidance": "Allowlist known enterprise subscription names with documented baseline.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "PERSIST_MALICIOUS_SERVICE_CREATION",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Suspicious Service Creation for Persistence",
        "description": "Detects new Windows service creation from non-standard paths or with encoded command lines indicating persistence via service abuse.",
        "severity": "high",
        "confidence": 0.79,
        "mitre_attack": ["T1543.003"],
        "event_types": ["security_event", "sysmon_event"],
        "required_fields": ["service_name", "service_path", "event_id"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|service_name",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Software installers frequently create services during installation.",
        "suppression_guidance": "Suppress services created by signed installers from known publishers.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "PERSIST_STARTUP_FOLDER_IMPLANT",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Startup Folder Persistence Implant",
        "description": "Detects file creation or modification in Windows startup folders by non-standard processes. Indicates persistence via startup folder chaining.",
        "severity": "medium",
        "confidence": 0.74,
        "mitre_attack": ["T1547.001"],
        "event_types": ["file_event"],
        "required_fields": ["file_path", "process_name", "user"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|file_path",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Software updaters may legitimately place items in startup folders.",
        "suppression_guidance": "Suppress known software updater processes by signed binary.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "PERSIST_SUSPICIOUS_SCHEDULED_TASK_LINEAGE",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Suspicious Scheduled Task Lineage",
        "description": "Detects scheduled task creation with unusual parent process lineage (e.g., spawned from document readers, browsers, or scripting engines).",
        "severity": "high",
        "confidence": 0.77,
        "mitre_attack": ["T1053.005"],
        "event_types": ["process_event", "sysmon_event"],
        "required_fields": ["process_name", "parent_process_name", "command_line"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|task_name",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Some enterprise tools schedule tasks from unusual parent processes.",
        "suppression_guidance": "Baseline known enterprise task creation patterns by parent process.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "PERSIST_REGISTRY_RUN_KEY_MASS_WRITE",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Mass Registry Run Key Write",
        "description": "Detects multiple run key entries written in rapid succession indicating automated persistence staging.",
        "severity": "high",
        "confidence": 0.76,
        "mitre_attack": ["T1547.001"],
        "event_types": ["registry_event"],
        "required_fields": ["registry_key", "registry_value", "process_name"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Software installers write multiple run keys during deployment.",
        "suppression_guidance": "Suppress during known software deployment windows.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "PERSIST_BOOT_SECTOR_MODIFICATION",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Boot Sector Modification Attempt",
        "description": "Detects raw disk write operations to boot sectors by non-OS processes indicating bootkit persistence.",
        "severity": "critical",
        "confidence": 0.91,
        "mitre_attack": ["T1542.003"],
        "event_types": ["sysmon_event", "process_event"],
        "required_fields": ["process_name", "disk_target", "access_type"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Disk imaging and repair tools write to boot sectors legitimately.",
        "suppression_guidance": "Suppress known disk utility processes by signed binary hash.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    # ── Defense Evasion (6) ────────────────────────────────────────────────────
    {
        "rule_id": "EVASION_TELEMETRY_SUPPRESSION_ATTEMPT",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Telemetry Suppression Attempt",
        "description": "Detects process attempts to disable, stop, or tamper with security agent services or event logging. Indicates deliberate telemetry suppression.",
        "severity": "critical",
        "confidence": 0.87,
        "mitre_attack": ["T1562.001", "T1562.006"],
        "event_types": ["process_event", "security_event"],
        "required_fields": ["process_name", "target_service", "command_line"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Software uninstallers may stop security services during removal.",
        "suppression_guidance": "Suppress only during documented maintenance windows with change ticket.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "EVASION_LOLBIN_CHAINING",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "LOLBin Chaining Pattern",
        "description": "Detects two or more living-off-the-land binaries executing in sequence within a short window indicating chained LOLBin abuse for evasion or execution.",
        "severity": "high",
        "confidence": 0.75,
        "mitre_attack": ["T1218", "T1059"],
        "event_types": ["process_event"],
        "required_fields": ["process_name", "parent_process_name", "command_line"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|host|user",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "IT administration scripts chain LOLBins legitimately.",
        "suppression_guidance": "Suppress for known admin script hashes from signed sources.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "EVASION_SIGNED_BINARY_PROXY",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Suspicious Signed Binary Proxy Execution",
        "description": "Detects signed Microsoft or vendor binaries used to proxy execution of unsigned payloads (e.g., mshta, regsvr32, wscript loading remote content).",
        "severity": "high",
        "confidence": 0.79,
        "mitre_attack": ["T1218.005", "T1218.010", "T1218.011"],
        "event_types": ["process_event", "network_event"],
        "required_fields": ["process_name", "command_line", "parent_process_name"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Legitimate HTA and COM-based automation tools use these binaries.",
        "suppression_guidance": "Suppress allowlisted scripts by hash in known deployment tooling.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "EVASION_PROCESS_MASQUERADING",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Process Name Masquerading",
        "description": "Detects processes whose names match known system utilities (svchost.exe, lsass.exe) but run from non-standard paths or with unexpected parent processes.",
        "severity": "high",
        "confidence": 0.86,
        "mitre_attack": ["T1036.005"],
        "event_types": ["process_event", "sysmon_event"],
        "required_fields": ["process_name", "process_path", "parent_process_name"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Some legitimate tools rename themselves to common process names.",
        "suppression_guidance": "Suppress by verified process hash rather than name.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "EVASION_DELAYED_EXECUTION_PATTERN",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Delayed Execution / Sandbox Evasion Pattern",
        "description": "Detects processes that sleep for extended periods (>60s) before executing a payload, indicating sandbox evasion via time-delay techniques.",
        "severity": "medium",
        "confidence": 0.68,
        "mitre_attack": ["T1497.003"],
        "event_types": ["process_event"],
        "required_fields": ["process_name", "sleep_duration", "command_line"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|process_name",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Legitimate polling-based tools sleep between iterations.",
        "suppression_guidance": "Suppress known polling agents by signed binary.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "EVASION_EVENT_LOG_CLEARANCE",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Windows Event Log Clearance",
        "description": "Detects clearing of Windows Security, System, or Application event logs by non-standard processes. Strong indicator of post-compromise evidence removal.",
        "severity": "critical",
        "confidence": 0.93,
        "mitre_attack": ["T1070.001"],
        "event_types": ["security_event"],
        "required_fields": ["event_id", "channel", "user", "process_name"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Compliance and log rotation tools may clear logs on schedule.",
        "suppression_guidance": "Suppress only for scheduled rotation processes with documented policy.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    # ── Lateral Movement (7) ──────────────────────────────────────────────────
    {
        "rule_id": "LATERAL_RDP_ANOMALOUS_SOURCE",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Anomalous RDP Source",
        "description": "Detects RDP connections originating from hosts that have never previously established RDP sessions or from unexpected internal subnets.",
        "severity": "high",
        "confidence": 0.74,
        "mitre_attack": ["T1021.001"],
        "event_types": ["network_event", "security_event"],
        "required_fields": ["source_ip", "dest_ip", "dest_port", "user"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|source_ip",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "New admin workstations or help-desk systems connecting to servers for the first time.",
        "suppression_guidance": "Suppress for known IT asset subnets with documented admin access patterns.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "LATERAL_SMB_PROPAGATION_CHAIN",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "SMB Lateral Propagation Chain",
        "description": "Detects a host connecting to three or more distinct SMB targets within a short window, indicating SMB-based lateral movement scanning or worm propagation.",
        "severity": "high",
        "confidence": 0.82,
        "mitre_attack": ["T1021.002"],
        "event_types": ["network_event"],
        "required_fields": ["source_ip", "dest_ip", "dest_port", "protocol"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|source_ip",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "File server backup and DFS replication generate high SMB fan-out.",
        "suppression_guidance": "Suppress known backup and replication server IPs.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "LATERAL_WINRM_UNUSUAL_CHAIN",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "WinRM Lateral Movement Chain",
        "description": "Detects WinRM/PS-Remoting connections from unexpected source hosts chained with process execution on remote targets, indicating WinRM-based lateral movement.",
        "severity": "high",
        "confidence": 0.78,
        "mitre_attack": ["T1021.006"],
        "event_types": ["network_event", "process_event"],
        "required_fields": ["source_ip", "dest_ip", "dest_port", "spawned_process"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|source_ip|dest_ip",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "PowerShell-based automation and orchestration tools use WinRM legitimately.",
        "suppression_guidance": "Allowlist known automation server IPs with documented PS-Remoting use.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "LATERAL_SSH_PROPAGATION_ANOMALY",
        "domain": "network",
        "status": "shadow",
        "version": "v1",
        "title": "SSH Propagation Anomaly",
        "description": "Detects SSH connections from a host that itself recently received an SSH connection, indicating SSH-based hop-chaining for lateral movement.",
        "severity": "high",
        "confidence": 0.76,
        "mitre_attack": ["T1021.004"],
        "event_types": ["network_event"],
        "required_fields": ["source_ip", "dest_ip", "dest_port", "timestamp"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|source_ip",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Jump hosts and bastion servers legitimately forward SSH connections.",
        "suppression_guidance": "Suppress known bastion host IPs with documented SSH forwarding policy.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "LATERAL_REMOTE_SERVICE_EXECUTION",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Remote Service Execution Chain",
        "description": "Detects a sequence of remote service creation followed by execution on multiple hosts within a short window indicating automated lateral spread via PSExec-style techniques.",
        "severity": "critical",
        "confidence": 0.84,
        "mitre_attack": ["T1569.002"],
        "event_types": ["security_event", "network_event"],
        "required_fields": ["source_host", "dest_host", "service_name", "event_id"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|source_host",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "SCCM, PDQ Deploy, and similar tools use remote service execution by design.",
        "suppression_guidance": "Suppress for known deployment tool hosts with documented use cases.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "LATERAL_DCOM_LATERAL_MOVEMENT",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "DCOM Lateral Movement",
        "description": "Detects DCOM object instantiation on remote machines spawning processes indicating lateral movement via DCOM execution.",
        "severity": "high",
        "confidence": 0.77,
        "mitre_attack": ["T1021.003"],
        "event_types": ["process_event", "network_event"],
        "required_fields": ["source_ip", "dest_ip", "dcom_object", "spawned_process"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|source_ip|dest_ip",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Enterprise management software uses DCOM for remote administration.",
        "suppression_guidance": "Suppress known management server source IPs.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "LATERAL_ADMIN_SHARE_STAGING",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Admin Share Staging for Lateral Movement",
        "description": "Detects file staging to admin shares (C$, ADMIN$, IPC$) from non-administrative hosts followed by remote execution, indicating lateral movement via admin share abuse.",
        "severity": "high",
        "confidence": 0.80,
        "mitre_attack": ["T1021.002", "T1570"],
        "event_types": ["network_event", "file_event"],
        "required_fields": ["source_ip", "dest_share", "file_name", "username"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|source_ip|dest_share",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "IT patch deployment may stage files via admin shares.",
        "suppression_guidance": "Suppress for known patch management system IP ranges.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    # ── Cloud / SaaS Abuse (7) ────────────────────────────────────────────────
    {
        "rule_id": "CLOUD_OAUTH_ABUSE_PROGRESSION",
        "domain": "cloud",
        "status": "shadow",
        "version": "v1",
        "title": "OAuth Token Abuse Progression",
        "description": "Detects OAuth token granted to an application followed by unusual API calls (mass export, admin consent) within the same session. Indicates OAuth phishing token abuse.",
        "severity": "high",
        "confidence": 0.79,
        "mitre_attack": ["T1550.001", "T1528"],
        "event_types": ["saas_event", "cloud_event"],
        "required_fields": ["app_id", "user", "scopes", "api_calls"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|app_id",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Newly deployed apps may request broad OAuth scopes for legitimate setup.",
        "suppression_guidance": "Suppress verified enterprise app registrations with IT approval.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CLOUD_ABNORMAL_API_TOKEN_USAGE",
        "domain": "cloud",
        "status": "shadow",
        "version": "v1",
        "title": "Abnormal API Token Usage Pattern",
        "description": "Detects API tokens used from geographically anomalous locations or at volumes significantly above the baseline for that token.",
        "severity": "high",
        "confidence": 0.76,
        "mitre_attack": ["T1078.004"],
        "event_types": ["cloud_event"],
        "required_fields": ["token_id", "source_ip", "api_endpoint", "request_count"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|token_id",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "New CI/CD pipelines or deployments may create anomalous baseline spikes.",
        "suppression_guidance": "Suppress during documented deployment events for known pipeline token IDs.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CLOUD_TENANT_ADMIN_ANOMALY",
        "domain": "cloud",
        "status": "shadow",
        "version": "v1",
        "title": "Suspicious Tenant Admin Activity",
        "description": "Detects tenant admin accounts performing privilege assignments, domain federation changes, or MFA policy modifications outside normal business hours.",
        "severity": "critical",
        "confidence": 0.83,
        "mitre_attack": ["T1098", "T1484.002"],
        "event_types": ["cloud_event", "saas_event"],
        "required_fields": ["user", "action", "target", "timestamp"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|user|action",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Emergency access accounts and break-glass operations may trigger outside hours.",
        "suppression_guidance": "Suppress documented break-glass accounts with ticketed evidence.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "SAAS_IMPOSSIBLE_ACTIVITY_CHAIN",
        "domain": "saas",
        "status": "shadow",
        "version": "v1",
        "title": "Impossible SaaS Activity Chaining",
        "description": "Detects SaaS activities (logins, file access, sharing) that chain across geographically impossible locations within a time window too short for physical travel.",
        "severity": "high",
        "confidence": 0.85,
        "mitre_attack": ["T1078.004"],
        "event_types": ["saas_event"],
        "required_fields": ["user", "source_ip", "action", "timestamp"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|user",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "VPN and proxy users may appear to be in geographically distant locations simultaneously.",
        "suppression_guidance": "Suppress known proxy/VPN egress IPs from impossible travel calculation.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "SAAS_MASS_EXPORT_ANOMALY",
        "domain": "saas",
        "status": "shadow",
        "version": "v1",
        "title": "Mass Data Export Anomaly",
        "description": "Detects bulk export or download of SaaS data (SharePoint, OneDrive, GSuite Drive) significantly exceeding the user's baseline download volume.",
        "severity": "high",
        "confidence": 0.77,
        "mitre_attack": ["T1530"],
        "event_types": ["saas_event"],
        "required_fields": ["user", "resource_count", "bytes_transferred", "action"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|user",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Employees preparing to transition roles may legitimately download large amounts of data.",
        "suppression_guidance": "Suppress for users with approved data migration requests.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CLOUD_RESOURCE_HIJACKING_PATTERN",
        "domain": "cloud",
        "status": "shadow",
        "version": "v1",
        "title": "Cloud Resource Hijacking Pattern",
        "description": "Detects rapid creation of compute or storage resources in unusual regions followed by data transfer activities. Indicates cloud resource hijacking for cryptomining or exfiltration.",
        "severity": "high",
        "confidence": 0.78,
        "mitre_attack": ["T1578", "T1537"],
        "event_types": ["cloud_event"],
        "required_fields": ["user", "resource_type", "region", "action"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|user|region",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Disaster recovery and multi-region deployments create resources in new regions legitimately.",
        "suppression_guidance": "Suppress for approved multi-region deployment events.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CLOUD_SERVICE_PRINCIPAL_ABUSE",
        "domain": "cloud",
        "status": "shadow",
        "version": "v1",
        "title": "Service Principal Credential Abuse",
        "description": "Detects service principal credentials used from interactive sessions or from IPs outside known automation infrastructure. Indicates stolen service principal abuse.",
        "severity": "high",
        "confidence": 0.82,
        "mitre_attack": ["T1078.004", "T1528"],
        "event_types": ["cloud_event"],
        "required_fields": ["principal_id", "source_ip", "session_type", "action"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|principal_id",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Developers may test service principals interactively during development.",
        "suppression_guidance": "Suppress known developer workstation IPs for service principals under active development.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    # ── Container / Runtime (6) ────────────────────────────────────────────────
    {
        "rule_id": "CONTAINER_PRIVESC_CHAIN",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Container Privilege Escalation Chain",
        "description": "Detects a container process that escalates privileges from a non-root user to root/UID-0 without a legitimate sudo or capability grant. Indicates container privilege escalation exploit.",
        "severity": "critical",
        "confidence": 0.84,
        "mitre_attack": ["T1611", "T1068"],
        "event_types": ["process_event"],
        "required_fields": ["container_id", "process_name", "uid_before", "uid_after"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|container_id",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Container entrypoint scripts may use gosu or su-exec to drop privileges in reverse.",
        "suppression_guidance": "Suppress for containers with documented privilege transition in entrypoint.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CONTAINER_RUNTIME_DRIFT",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Container Runtime Drift Anomaly",
        "description": "Detects containers running processes, writing files, or making network connections not observed during a baseline period. Indicates runtime drift from expected container behavior.",
        "severity": "medium",
        "confidence": 0.70,
        "mitre_attack": ["T1610"],
        "event_types": ["process_event", "file_event", "network_event"],
        "required_fields": ["container_id", "image_name", "process_name", "drift_type"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|image_name",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Auto-updating containers may exhibit drift after pulling new layers.",
        "suppression_guidance": "Suppress during documented rolling update windows.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CONTAINER_PRIVILEGED_EXEC_CHAINING",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Privileged Container Exec Chaining",
        "description": "Detects a kubectl exec or docker exec into a privileged container followed by host namespace access, indicating container escape via privileged exec.",
        "severity": "critical",
        "confidence": 0.88,
        "mitre_attack": ["T1611"],
        "event_types": ["process_event"],
        "required_fields": ["container_id", "privileged", "host_namespace", "command"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|container_id",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Debug-mode containers may be intentionally privileged for troubleshooting.",
        "suppression_guidance": "Suppress containers in named debug namespaces with documented approval.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CONTAINER_SUSPICIOUS_IMAGE_LINEAGE",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Suspicious Container Image Lineage",
        "description": "Detects containers spawned from images pulled from untrusted or non-standard registries outside the organizational allowlist.",
        "severity": "high",
        "confidence": 0.82,
        "mitre_attack": ["T1525"],
        "event_types": ["process_event"],
        "required_fields": ["image_registry", "image_name", "image_digest", "container_id"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|image_registry",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Development environments may pull from public registries by design.",
        "suppression_guidance": "Suppress in development namespace; require approved registries in production.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CONTAINER_ABNORMAL_RUNTIME_PERSISTENCE",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Abnormal Container Runtime Persistence",
        "description": "Detects writes to container host mounts (/etc/cron.d, /proc/sysrq-trigger, host /tmp) from within containers indicating attempted host persistence via container breakout.",
        "severity": "critical",
        "confidence": 0.89,
        "mitre_attack": ["T1611", "T1547"],
        "event_types": ["file_event"],
        "required_fields": ["container_id", "file_path", "mount_type", "process_name"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|container_id",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Volume-mounted log aggregation containers write to host paths intentionally.",
        "suppression_guidance": "Suppress log agent containers with documented host mount requirements.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
    {
        "rule_id": "CONTAINER_HOST_NETWORK_NAMESPACE_ABUSE",
        "domain": "endpoint",
        "status": "shadow",
        "version": "v1",
        "title": "Container Host Network Namespace Abuse",
        "description": "Detects containers running with hostNetwork: true that initiate connections to unusual internal services, indicating host network namespace abuse for lateral movement.",
        "severity": "high",
        "confidence": 0.80,
        "mitre_attack": ["T1611", "T1021"],
        "event_types": ["network_event", "process_event"],
        "required_fields": ["container_id", "host_network", "dest_ip", "dest_port"],
        "output_topic": "xdr.alerts.shadow",
        "shadow_only": True,
        "suppression_key": "rule_id|container_id",
        "replay_fixture": None,
        "expected_alert_count": None,
        "false_positive_notes": "Network monitoring and CNI plugin containers require hostNetwork.",
        "suppression_guidance": "Suppress known CNI and monitoring containers by image name from trusted registry.",
        "owner": "detection-engineering",
        "validation_evidence": None,
        "created_at": "2026-05-22T00:00:00Z",
        "updated_at": "2026-05-22T00:00:00Z"
    },
]

with open('docs/detection/rules/registry.v1.json') as f:
    registry = json.load(f)

existing_ids = {r['rule_id'] for r in registry['rules']}
added = 0
for rule in NEW_RULES:
    if rule['rule_id'] not in existing_ids:
        registry['rules'].append(rule)
        added += 1

print(f"Added {added} rules. Total: {len(registry['rules'])}")

with open('docs/detection/rules/registry.v1.json', 'w') as f:
    json.dump(registry, f, indent=2)
    f.write('\n')

print("Registry written.")
